apiVersion: v1
kind: Pod
metadata:
  name: cats-service
  labels:
    app: cats-service
spec:
  containers:
  - name: cats-service
    image: robertojrojas/cats-service:0.3
    args:
      - "-http=0.0.0.0:8091"
    ports:
      - containerPort: 8091
    env:
      - name: MYSQL_HOST
        valueFrom:
          configMapKeyRef:
            name: mysql-config
            key: mysql.host
      - name: MYSQL_PORT
        valueFrom:
          configMapKeyRef:
            name: mysql-config
            key: mysql.port
      - name: MYSQL_DBNAME
        valueFrom:
          configMapKeyRef:
            name: mysql-config
            key: mysql.dbname
      - name: MYSQL_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: username
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: password
  volumes:
  - name: mysql-secrets
    secret:
      secretName: mysql-secrets
