FROM easypi/alpine-arm:3.4
MAINTAINER Roberto J. Rojas <robertojrojas@gmail.com>

ADD birds-service /usr/bin/birds-service

ENV POSTGRESQL_DB_URI "user=birdman password=mycape dbname=birddb sslmode=disable"

ENTRYPOINT ["birds-service"]